Repository ACON3D/ABLER, pull requests merged in 2021-12, with the labels that each got.

#20 백그라운드 옵션을 켜도 에러가 나지 않게 수정
  release/scripts/startup/abler/__init__.py
  release/scripts/startup/abler/pref.py
Labels: enhancement

#27 .env로 token 변경
  .gitignore
  abler_requirements.txt
  build_files/windows/check_libraries.cmd
  build_files/windows/find_dependencies.cmd
  release/scripts/startup/abler/lib/tracker/__init__.py
  release/scripts/startup/abler/lib/tracker/_mixpanel.py
  release/scripts/startup/abler/lib/tracker/_sentry.py
Labels: enhancement

#35 컨버터 브랜치에 .env gitignore 추가
  .gitignore
Labels: bug

#51 add groups in tree structure
  release/scripts/startup/abler/layer_control.py
Labels: enhancement

#49 separate file open & login auto
  abler_requirements.txt
  release/scripts/startup/abler/credential_modal.py
  release/scripts/startup/abler/lib/login.py
  release/scripts/startup/abler/lib/post_open.py
Labels: tracker

#43 tracker use_state
  release/scripts/startup/abler/lib/objects.py
  release/scripts/startup/abler/lib/tracker/_tracker.py
Labels: tracker

#44 tracker bloom prop button
  release/scripts/startup/abler/custom_properties.py
  release/scripts/startup/abler/face_control.py
  release/scripts/startup/abler/lib/scenes.py
  release/scripts/startup/abler/lib/tracker/_tracker.py
Labels: tracker

#45 tracker Depth of Field & Background Images
  release/scripts/startup/abler/camera_control.py
  release/scripts/startup/abler/custom_properties.py
  release/scripts/startup/abler/lib/scenes.py
  release/scripts/startup/abler/lib/tracker/_tracker.py
Labels: tracker

#39 타입 어노테이션 테스트를 위한 브랜치
  release/scripts/startup/abler/lib/cameras.py
  release/scripts/startup/abler/lib/scenes.py
  release/scripts/startup/abler/lib/shadow.py
Labels: documentation, enhancement

#53 메인 브랜치에 타이핑 추가 + 오타 수정
  release/scripts/startup/abler/custom_properties.py
  release/scripts/startup/abler/lib/cameras.py
  release/scripts/startup/abler/lib/scenes.py
  release/scripts/startup/abler/lib/shadow.py
Labels: documentation, enhancement
