Repository ACON3D/ABLER, pull requests merged in 2022-02, with the labels that each got.

#84 필요한 오퍼레이터에 UNDO 옵션 추가
  release/scripts/startup/abler/camera_control.py
  release/scripts/startup/abler/face_control.py
  release/scripts/startup/abler/general.py
  release/scripts/startup/abler/layer_control.py
  release/scripts/startup/abler/object_control.py
  release/scripts/startup/abler/render_control.py
  release/scripts/startup/abler/scene_control.py
Labels: enhancement

#88 렌더시 태양 강도가 변경
  release/scripts/startup/abler/lib/post_open.py
Labels: bug

#90 가독성 있도록 살짝 리팩토링
  release/scripts/startup/abler/__init__.py
  release/scripts/startup/abler/credential_modal.py
  release/scripts/startup/abler/custom_properties.py
  release/scripts/startup/abler/face_control.py
  release/scripts/startup/abler/layer_control.py
  release/scripts/startup/abler/object_control.py
  release/scripts/startup/abler/render_control.py
Labels: refactor

#93 Typing part 2
  release/scripts/startup/abler/lib/async_task.py
  release/scripts/startup/abler/lib/cameras.py
  release/scripts/startup/abler/lib/config_env.py
  release/scripts/startup/abler/lib/login.py
  release/scripts/startup/abler/lib/materials/materials_handler.py
  release/scripts/startup/abler/lib/objects.py
  release/scripts/startup/abler/lib/post_open.py
  release/scripts/startup/abler/lib/remember_username.py
  release/scripts/startup/abler/lib/render.py
  release/scripts/startup/abler/lib/scenes.py
  release/scripts/startup/abler/lib/shadow.py
Labels: refactor
