Repository ACON3D/ABLER, pull requests merged in 2022-03, with the labels that each got.

#103 render control 리팩토링
  release/scripts/startup/abler/render_control.py
Labels: refactor

#107 abler_dev_build 파일 추가
  abler_dev_build.py
Labels: enhancement

#105 그룹 내비게이션 오퍼레이터
  release/scripts/modules/addon_utils.py
  release/scripts/startup/abler/__init__.py
  release/scripts/startup/abler/layer_control.py
  release/scripts/startup/abler/lib/layers.py
  release/scripts/startup/abler/lib/tracker/_tracker.py
  release/scripts/startup/abler/object_control.py
Labels: enhancement

#48 그룹 내비게이션 기능 to main branch
  .pre-commit-config.yaml
  release/datafiles/locale/po/ko.po
  release/scripts/modules/addon_utils.py
  release/scripts/startup/abler/__init__.py
  release/scripts/startup/abler/custom_properties.py
  release/scripts/startup/abler/general.py
  release/scripts/startup/abler/layer_control.py
  release/scripts/startup/abler/lib/layers.py
  release/scripts/startup/abler/lib/materials/materials_handler.py
  release/scripts/startup/abler/lib/objects.py
  release/scripts/startup/abler/lib/scenes.py
  release/scripts/startup/abler/lib/tracker/_tracker.py
  release/scripts/startup/abler/object_control.py
  release/scripts/startup/abler/operators.py
  release/scripts/startup/abler/pref.py
Labels: enhancement

#113 그룹 내비게이션 무한루프 버그 픽스
  release/scripts/startup/abler/lib/layers.py
Labels: bug

#115 General에 Save Operator 추가
  release/datafiles/locale/po/ko.po
  release/scripts/startup/abler/general.py
  release/scripts/startup/abler/lib/tracker/_tracker.py
Labels: enhancement

#121 fix compositor background image transform calculation
  release/scripts/startup/abler/lib/render.py
Labels: bug
